[2025-07-06T15:48:11.360+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=0 [queued]>
[2025-07-06T15:48:11.365+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=0 [queued]>
[2025-07-06T15:48:11.365+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-07-06T15:48:11.371+0000] {taskinstance.py:1380} INFO - Executing <Mapped(_PythonDecoratedOperator): download_and_process> on 2025-07-06 15:38:10.058241+00:00
[2025-07-06T15:48:11.374+0000] {standard_task_runner.py:57} INFO - Started process 528 to run task
[2025-07-06T15:48:11.375+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'download_and_process', 'manual__2025-07-06T15:38:10.058241+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpl9g179rn', '--map-index', '0']
[2025-07-06T15:48:11.377+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask download_and_process
[2025-07-06T15:48:11.385+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T15:48:11.404+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=0 [running]> on host 2331dcd11242
[2025-07-06T15:48:11.788+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='download_and_process' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T15:38:10.058241+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T15:38:10.058241+00:00'
[2025-07-06T15:48:11.790+0000] {logging_mixin.py:151} INFO - Starting download of 2020.csv.gz
[2025-07-06T15:48:11.793+0000] {base.py:73} INFO - Using connection ID 'noaa_http' for task execution.
[2025-07-06T15:48:11.793+0000] {logging_mixin.py:151} INFO - Downloading from: https://www.ncei.noaa.gov//pub/data/ghcn/daily/by_year/2020.csv.gz
[2025-07-06T15:48:11.796+0000] {base.py:73} INFO - Using connection ID 'noaa_http' for task execution.
[2025-07-06T16:07:55.180+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-06T16:07:55.214+0000] {process_utils.py:131} INFO - Sending 15 to group 528. PIDs of all processes in the group: [528]
[2025-07-06T16:07:55.215+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 528
[2025-07-06T16:07:55.216+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-06T16:07:55.293+0000] {logging_mixin.py:151} INFO - Error downloading 2020.csv.gz: Task received SIGTERM signal
[2025-07-06T16:07:55.408+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=528, status='terminated', exitcode=0, started='15:48:11') (528) terminated with exit code 0
