[2025-07-06T15:48:07.932+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=3 [queued]>
[2025-07-06T15:48:07.935+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=3 [queued]>
[2025-07-06T15:48:07.935+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-07-06T15:48:07.940+0000] {taskinstance.py:1380} INFO - Executing <Mapped(_PythonDecoratedOperator): download_and_process> on 2025-07-06 15:38:10.058241+00:00
[2025-07-06T15:48:07.943+0000] {standard_task_runner.py:57} INFO - Started process 519 to run task
[2025-07-06T15:48:07.945+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'download_and_process', 'manual__2025-07-06T15:38:10.058241+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp71c7jngv', '--map-index', '3']
[2025-07-06T15:48:07.946+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask download_and_process
[2025-07-06T15:48:07.953+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T15:48:07.967+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-06T15:38:10.058241+00:00 map_index=3 [running]> on host 2331dcd11242
[2025-07-06T15:48:08.109+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='download_and_process' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T15:38:10.058241+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T15:38:10.058241+00:00'
[2025-07-06T15:48:08.109+0000] {logging_mixin.py:151} INFO - Starting download of 2023.csv.gz
[2025-07-06T15:48:08.112+0000] {base.py:73} INFO - Using connection ID 'noaa_http' for task execution.
[2025-07-06T15:48:08.112+0000] {logging_mixin.py:151} INFO - Downloading from: https://www.ncei.noaa.gov//pub/data/ghcn/daily/by_year/2023.csv.gz
[2025-07-06T15:48:08.114+0000] {base.py:73} INFO - Using connection ID 'noaa_http' for task execution.
[2025-07-06T16:07:57.091+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-06T16:07:57.096+0000] {process_utils.py:131} INFO - Sending 15 to group 519. PIDs of all processes in the group: [519]
[2025-07-06T16:07:57.096+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 519
[2025-07-06T16:07:57.097+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-06T16:07:57.105+0000] {logging_mixin.py:151} INFO - Error downloading 2023.csv.gz: Task received SIGTERM signal
[2025-07-06T16:07:57.163+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=519, status='terminated', exitcode=0, started='15:48:07') (519) terminated with exit code 0
